import localFont from "next/font/local";
import "../assets/globals.css";

const hubot = localFont({
  src: "./Hubot-Sans.woff2",
  display: "swap",
});

export const metadata = {
  title: "Diego Do Santos | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={`antialiased ${hubot.className}`}>
      <body className="bg-[#101012]">{children}</body>
    </html>
  );
}
