import localFont from "next/font/local";
import "../assets/globals.css";

const hubot = localFont({
  src: "./Hubot-Sans.woff2",
});

export const metadata = {
  title: "Diego Do Santos | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={`antialiased ${hubot.className}`}>
      <head>
        <script
          id="counterscale-config"
          dangerouslySetInnerHTML={{
            __html: `(function () {
  window.counterscale = {
    q: [["set", "siteId", "hl-estudio"], ["trackPageview"]],
  };
})();`,
          }}
        />
        <script
          id="counterscale-script"
          src="https://counterscale.drumpy.workers.dev/tracker.js"
          defer
        />
      </head>
      <body className="bg-[#101012]">{children}</body>
    </html>
  );
}
